url: https://mystic-mimi.github.io
baseurl: /dev/

# Site settings
title: Mystic Mimi
email: mystic.mimi.nft@gmail.com
description: "..."


# Team names, titles and social links
people:
- name: Tom Smith
  pic: 1
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Page
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: discord
      url: 
    - title: linkedin
      url: #

- name: Neil Armstrong
  pic: 3
  position: Astronaut
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MysticMimiNFT
  - title: bolt
    url: http://discord.gg/uNEVvRmaE8
  - title: instagram
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
